### ISSUE TITLE
Error al compilar en Vercel debido a valores no leídos en Login.tsx

### ISSUE THREAD

**Issue by vngerus** [vngerus/BurgerCat_DevOps_Projects#1]
Al intentar desplegar el proyecto en Vercel, se generaron varios errores relacionados con variables declaradas pero no utilizadas en el archivo Login.tsx. A continuación se muestra el log del error:

![imagen_2024-10-03_222544827](https://github.com/user-attachments/assets/3e019a82-4285-4fc0-89a7-eb4c401c83bb)

**Comment by Galo89** [comment]
#1 Resuelto

![image](https://github.com/user-attachments/assets/9dc266ed-3947-4e62-a980-cc7ccfca3b25)
